[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "fx_library_pro"
version = "1.0.2"
description = "this moudel is fx library pro"
readme = "README.md"
authors = [
    {name = "Arsha"}
]


[project.urls]
Homepage = "https://github.com/arshadadvar-afk/fx_library___pro"
Issues = "https://github.com/arshadadvar-afk/fx_library___pro/issues"
